version: '3'
services:
  host:
    build: .
    deploy:
      replicas: 1
    command: tox -e py36-a28,py37-a28,py38-a28,py39-a28,py36-a29,py37-a29,py38-a29,py39-a29
    depends_on:
      - target1
      - target2
    volumes:
      - .:/suitable
    network_mode: host
  target1:
    build:
      context: .
      dockerfile: Dockerfile.target 
    ports:
      - "9999:22"
  target2:
    build:
      context: .
      dockerfile: Dockerfile.target 
    ports:
      - "8888:22"
