version: '3'
services:
  # host:
  #   build: .
  #   depends_on:
  #     - target1
  #     - target2
  #   volumes:
  #     - .:/suitable
  target1:
    build:
      context: .
      dockerfile: Dockerfile.target 
    ports:
      - "9999:22"
  target2:
    build:
      context: .
      dockerfile: Dockerfile.target 
    ports:
      - "8888:22"
