version: '3'
services:
  host:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    command: tox -vvv -e py36-a210
    # command: tox -e py36-a28,py36-a29,py36-a210,py36-a211,py36-a212,py36-a213,py36-a300,py36-a400,py36-a500,py36-a600
    environment:
      - ANSIBLE_SKIP_CONFLICT_CHECK=1
    depends_on:
      - target1
      - target2
    volumes:
      - ../:/suitable
    network_mode: host
  target1:
    build:
      context: .
      dockerfile: Dockerfile.target 
    ports:
      - "9999:22"
  target2:
    build:
      context: .
      dockerfile: Dockerfile.target 
    ports:
      - "8888:22"
